version: "3.7"
services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - "4000:4000"
    env_file:
      - .env.production
    depends_on:
      - mongo
    volumes:
      - appdata:/app/public
      - ./src:/app/src
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pokemon456
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/app.prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - rest-api
      - certbot
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/_letsencrypt
      - ./certbot/log:/var/log
    # command: certonly --webroot -w /var/www --force-renewal --email haris.wm23@gmail.com -d poke-api.online --agree-tos
    command: certonly --webroot -w /var/www/_letsencrypt --email haris.wm23@gmail.com -d www.poke-api.online --agree-tos --renew-by-default
volumes:
  dbdata6:
  appdata:
