version: "3.7"
services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - "4000:4000"
    env_file:
      - .env.production
    depends_on:
      - mongo
      - redis
    volumes:
      - appdata:/app/public
      - ./src:/app/src
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
  redis:
    image: redis:alpine
    container_name: redis-client
    ports:
      - "6379:6379"
volumes:
  dbdata6:
  appdata:
