version: "3.7"
services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    build:
      context: ./
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - appdata:/app/public
      - ./src:/app/src
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
  appdata:
