version: "3.7"
services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - "4000:4000"
    env_file:
      - .env.production
    depends_on:
      - mongo
    volumes:
      - appdata:/app/public
      - ./src:/app/src
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pokemon456
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/app.conf:/etc/nginx/nginx.conf
    depends_on:
      - rest-api
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos

volumes:
  dbdata6:
  appdata:
